
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "1.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/now"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.3"

[[constraint]]
  name = "github.com/ktrysmt/go-bitbucket"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/mrjones/oauth"

[[constraint]]
  name = "github.com/requilence/jobs"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/vova616/xxhash"

[[constraint]]
  branch = "master"
  name = "github.com/weekface/mgorus"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "0.6.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "master"
  name = "github.com/requilence/telegram-bot-api"

[[constraint]]
  branch = "master"
  name = "github.com/toby3d/go-telegraph"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"
